name: Android x86_64 Build Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: |
        source ./android_env.sh x86_64
        ./configure --host=$CHOST
    - name: make
      run: make
